 given a nxm matrix with numberical entries
 for each cell. Find the shortest path from cell (0,0)
to cell (n-1,m-1). You are allowed to move right or down only (no left or up)
the final cost of reaching a given cell is the sum of all costs of the cells
on its path, including itself. 


In [1]:
import numpy as np 
n=4
m=4
cost=np.array([[3,6,1,4],[2,9,1,4],[5,3,9,2],[4,4,6,2]])

T=np.zeros((n,m))
T[0][0]=cost[0][0]


In [2]:
for j in range(1,m):
    T[0][j]=T[0][j-1]+cost[0][j]
for i in range(1,n):
    T[i][0]=T[i-1][0]+cost[i][0]

for i in range(1,n):
    for j in range(1,m):
        T[i][j]+=cost[i][j]+min(T[i][j-1],T[i-1][j])

In [3]:
print(T)

[[ 3.  9. 10. 14.]
 [ 5. 14. 11. 15.]
 [10. 13. 20. 17.]
 [14. 17. 23. 19.]]
